desktop_file = 'io.github.sugarycandybar.Carabiner.desktop'
install_data(desktop_file,
  install_dir: get_option('datadir') / 'applications'
)

metainfo_file = 'io.github.sugarycandybar.Carabiner.metainfo.xml'
install_data(metainfo_file,
  install_dir: get_option('datadir') / 'metainfo'
)

# Icons
install_data('icons/hicolor/scalable/apps/io.github.sugarycandybar.Carabiner.svg',
  install_dir: get_option('datadir') / 'icons/hicolor/scalable/apps'
)

install_data('icons/hicolor/symbolic/apps/io.github.sugarycandybar.Carabiner-symbolic.svg',
  install_dir: get_option('datadir') / 'icons/hicolor/symbolic/apps'
)
